// Generated by showcase-product/src/generate.ts. Do not edit.
module GeneratedCircleKitShowcase {
    const PRODUCT_ID = "circlekit-showcase";
    const PRODUCT_LABEL = "CIRCLEKIT";
    const PRODUCT_SPEC_VERSION = "0.3.24";
    const SCREEN_ID = "section.controls";
    const SURFACE_CLASS = "round";
    const SURFACE_LABEL = "ROUND";
    const COMPONENT_ID = "control.progress";
    const COMPONENT_ID_LABEL = "CONTROL.PROGRESS";
    const COMPONENT_LABEL = "PROGRESS";
    const COMPONENT_ORDER = 3;
    const COMPONENT_ORDER_LABEL = "ORDER 3";
    const COMPONENT_RENDERER = 1;
    const SCENARIO_ID = "half";
    const SCENARIO_LABEL = "50 PERCENT";
    const PALETTE_REF = "sea-glass";
    const FOOTER_LABEL = "SEA-GLASS  ORDER 3";
    const ICON_REF = "download";
    const PALETTE_RENDERER = 1;
    const ICON_RENDERER = 1;
}
