// Generated by showcase-product/src/generate.ts. Do not edit.
module GeneratedCircleKitShowcase {
    const PRODUCT_ID = "circlekit-showcase";
    const PRODUCT_LABEL = "CIRCLEKIT";
    const PRODUCT_SPEC_VERSION = "0.3.31";
    const ARTIFACT_ID = "garmin-limited-ui";
    const RENDERER_ID = "garmin-connectiq-monkeyc";
    const SCREEN_ID = "artifact.garmin-limited-ui";
    const SURFACE_CLASS = "round";
    const SURFACE_LABEL = "ROUND";
    const COMPONENT_ID = "control.progress";
    const COMPONENT_ID_LABEL = "CONTROL.PROGRESS";
    const COMPONENT_LABEL = "PROGRESS";
    const COMPONENT_ORDER = 0;
    const SCENARIO_ID = "none";
    const SCENARIO_LABEL = "NONE";
    const ACTIVE_TICKS = 0;
    const PALETTE_REF = "";
    const FOOTER_LABEL = "INHERITED  ORDER 0";
    const ICON_REF = "showcase.download";
    const ICON_ASSET_REF = "download";
    const COLOR_SURFACE = 0x000000;
    const COLOR_ACTION = 0xF1EFE9;
    const COLOR_MUTED = 0xA4A49F;
    const COLOR_FAINT = 0x727579;
    const COLOR_LINE = 0x232527;
    const COLOR_ICON = 0xF1EFE9;
    const ICON_VIEWPORT_WIDTH = 24;
    const ICON_VIEWPORT_HEIGHT = 24;
    var ICON_FILL_PATHS = [[[10.2, 3.5], [13.8, 3.5], [13.8, 9.5], [16.6, 9.5], [12, 15.5], [7.4, 9.5], [10.2, 9.5]]];
    var ICON_STROKE_PATHS = [[[4.5, 19.5], [19.5, 19.5]]];
    var ICON_STROKE_WIDTHS = [2.8];
}
