// GENERATED from circlekit-assets/src/ring-icon-assets.ts - do not edit.
package com.adelost.designkit.ui

internal val PORTABLE_RING_ICON_ACCENTS: Map<String, CircleAccent> = mapOf(
    "arrow" to CircleAccent.SKY,
    "cloud" to CircleAccent.CLOUD,
    "plane" to CircleAccent.SKY,
    "gps" to CircleAccent.POSITIVE,
    "map" to CircleAccent.SKY,
    "mountain" to CircleAccent.COLD,
    "sun" to CircleAccent.SUN,
    "book" to CircleAccent.ACHIEVEMENT,
    "wrench" to CircleAccent.CAUTION,
    "sliders" to CircleAccent.VIOLET,
    "ruler" to CircleAccent.POSITIVE,
    "gear" to CircleAccent.VIOLET,
    "chute" to CircleAccent.SKY,
    "activity" to CircleAccent.POSITIVE,
    "eye" to CircleAccent.SKY,
    "eye-off" to CircleAccent.SKY,
    "speaker" to CircleAccent.SKY,
    "wifi" to CircleAccent.SKY,
    "refresh" to CircleAccent.SKY,
    "check" to CircleAccent.POSITIVE,
    "warning" to CircleAccent.CAUTION,
    "clown" to CircleAccent.VIOLET,
    "trash" to CircleAccent.DANGER,
    "target" to CircleAccent.POSITIVE,
    "gauge" to CircleAccent.CAUTION,
    "bell" to CircleAccent.CAUTION,
    "link" to CircleAccent.SKY,
    "vibrate" to CircleAccent.VIOLET,
    "download" to CircleAccent.POSITIVE,
    "layers" to CircleAccent.VIOLET,
    "cube" to CircleAccent.VIOLET,
    "palette" to CircleAccent.VIOLET,
    "plus" to CircleAccent.POSITIVE,
    "minus" to CircleAccent.CAUTION,
    "chart" to CircleAccent.POSITIVE,
    "ground-track" to CircleAccent.SKY,
    "spatial-path" to CircleAccent.VIOLET,
    "sink-rate" to CircleAccent.RAIN,
    "gps-points" to CircleAccent.POSITIVE,
    "gps-break" to CircleAccent.CAUTION,
    "touchdown-run" to CircleAccent.POSITIVE,
    "touchdown-sink" to CircleAccent.RAIN,
    "yaw" to CircleAccent.SKY,
    "pitch" to CircleAccent.ACHIEVEMENT,
    "roll" to CircleAccent.VIOLET,
    "rotation-rate" to CircleAccent.CAUTION,
    "clock" to CircleAccent.VIOLET,
    "wind" to CircleAccent.RAIN,
    "flag" to CircleAccent.ACHIEVEMENT,
    "moon" to CircleAccent.COLD,
    "calendar" to CircleAccent.POSITIVE,
    "star" to CircleAccent.ACHIEVEMENT,
    "cloud-sun" to CircleAccent.SUN,
    "cloud-sun-sun" to CircleAccent.SUN,
    "cloud-sun-cloud" to CircleAccent.CLOUD,
    "rain-cloud" to CircleAccent.CLOUD,
    "rain-drops" to CircleAccent.RAIN,
    "storm-cloud" to CircleAccent.CLOUD,
    "storm-bolt" to CircleAccent.DANGER,
    "rain" to CircleAccent.RAIN,
    "snow" to CircleAccent.COLD,
    "storm" to CircleAccent.DANGER,
    "fog" to CircleAccent.CLOUD,
    "thermometer" to CircleAccent.COLD,
    "chevron-left" to CircleAccent.NEUTRAL,
    "freefly" to CircleAccent.NEUTRAL,
    "head-down" to CircleAccent.NEUTRAL,
    "belly-arch" to CircleAccent.NEUTRAL,
    "pencil" to CircleAccent.VIOLET,
    "zigzag" to CircleAccent.CAUTION,
    "cross" to CircleAccent.DANGER,
    "chevron-right" to CircleAccent.NEUTRAL,
    "chevron-up" to CircleAccent.NEUTRAL,
    "chevron-down" to CircleAccent.NEUTRAL,
    "home" to CircleAccent.SKY,
    "lock" to CircleAccent.NEUTRAL,
    "record" to CircleAccent.DANGER,
    "stop" to CircleAccent.DANGER,
    "grid" to CircleAccent.SKY,
    "watch" to CircleAccent.VIOLET,
    "play" to CircleAccent.NEUTRAL,
    "pause" to CircleAccent.NEUTRAL,
    "phone" to CircleAccent.VIOLET,
)

internal val PORTABLE_RING_ICON_CATALOG = listOf(
    RingIcons.Arrow,
    RingIcons.Cloud,
    RingIcons.Plane,
    RingIcons.Gps,
    RingIcons.Map,
    RingIcons.Mountain,
    RingIcons.Sun,
    RingIcons.Book,
    RingIcons.Wrench,
    RingIcons.Sliders,
    RingIcons.Ruler,
    RingIcons.Gear,
    RingIcons.Chute,
    RingIcons.Activity,
    RingIcons.Eye,
    RingIcons.EyeOff,
    RingIcons.Speaker,
    RingIcons.Wifi,
    RingIcons.Refresh,
    RingIcons.Check,
    RingIcons.Warning,
    RingIcons.Clown,
    RingIcons.Trash,
    RingIcons.Target,
    RingIcons.Gauge,
    RingIcons.Bell,
    RingIcons.Link,
    RingIcons.Vibrate,
    RingIcons.Download,
    RingIcons.Layers,
    RingIcons.Cube,
    RingIcons.Palette,
    RingIcons.Plus,
    RingIcons.Minus,
    RingIcons.Chart,
    RingIcons.GroundTrack,
    RingIcons.SpatialPath,
    RingIcons.SinkRate,
    RingIcons.GpsPoints,
    RingIcons.GpsBreak,
    RingIcons.TouchdownRun,
    RingIcons.TouchdownSink,
    RingIcons.Yaw,
    RingIcons.Pitch,
    RingIcons.Roll,
    RingIcons.RotationRate,
    RingIcons.Clock,
    RingIcons.Wind,
    RingIcons.Flag,
    RingIcons.Moon,
    RingIcons.Calendar,
    RingIcons.Star,
    RingIcons.CloudSun,
    RingIcons.CloudSunSun,
    RingIcons.CloudSunCloud,
    RingIcons.RainCloud,
    RingIcons.RainDrops,
    RingIcons.StormCloud,
    RingIcons.StormBolt,
    RingIcons.Rain,
    RingIcons.Snow,
    RingIcons.Storm,
    RingIcons.Fog,
    RingIcons.Thermometer,
    RingIcons.ChevronLeft,
    RingIcons.Freefly,
    RingIcons.HeadDown,
    RingIcons.BellyArch,
    RingIcons.Pencil,
    RingIcons.Zigzag,
    RingIcons.Cross,
    RingIcons.ChevronRight,
    RingIcons.ChevronUp,
    RingIcons.ChevronDown,
    RingIcons.Home,
    RingIcons.Lock,
    RingIcons.Record,
    RingIcons.Stop,
    RingIcons.Grid,
    RingIcons.Watch,
    RingIcons.Play,
    RingIcons.Pause,
    RingIcons.Phone,
)

internal val PORTABLE_COMPOSITE_ICON_STYLES: Map<String, CircleIconStyle> by lazy { mapOf(
    "cloud-sun" to CircleIconStyle(listOf(CircleIconLayer(RingIcons.CloudSunSun, CircleAccent.SUN), CircleIconLayer(RingIcons.CloudSunCloud, CircleAccent.CLOUD)), primaryAccent = CircleAccent.SUN),
    "rain" to CircleIconStyle(listOf(CircleIconLayer(RingIcons.RainCloud, CircleAccent.CLOUD), CircleIconLayer(RingIcons.RainDrops, CircleAccent.RAIN)), primaryAccent = CircleAccent.RAIN),
    "storm" to CircleIconStyle(listOf(CircleIconLayer(RingIcons.StormCloud, CircleAccent.CLOUD), CircleIconLayer(RingIcons.StormBolt, CircleAccent.DANGER)), primaryAccent = CircleAccent.DANGER),
) }
