// GENERATED from circlekit-assets/src/ring-icon-assets.ts - do not edit.
package com.adelost.designkit.ui

internal val PORTABLE_RING_ICON_CATALOG = listOf(
    RingIcons.Arrow,
    RingIcons.Cloud,
    RingIcons.Plane,
    RingIcons.Gps,
    RingIcons.Map,
    RingIcons.Mountain,
    RingIcons.Sun,
    RingIcons.Book,
    RingIcons.Wrench,
    RingIcons.Sliders,
    RingIcons.Ruler,
    RingIcons.Gear,
    RingIcons.Chute,
    RingIcons.Activity,
    RingIcons.Eye,
    RingIcons.EyeOff,
    RingIcons.Speaker,
    RingIcons.Wifi,
    RingIcons.Refresh,
    RingIcons.Check,
    RingIcons.Warning,
    RingIcons.Clown,
    RingIcons.Trash,
    RingIcons.Target,
    RingIcons.Gauge,
    RingIcons.Bell,
    RingIcons.Link,
    RingIcons.Vibrate,
    RingIcons.Download,
    RingIcons.Layers,
    RingIcons.Cube,
    RingIcons.Palette,
    RingIcons.Plus,
    RingIcons.Minus,
    RingIcons.Chart,
    RingIcons.GroundTrack,
    RingIcons.SpatialPath,
    RingIcons.SinkRate,
    RingIcons.GpsPoints,
    RingIcons.GpsBreak,
    RingIcons.TouchdownRun,
    RingIcons.TouchdownSink,
    RingIcons.Yaw,
    RingIcons.Pitch,
    RingIcons.Roll,
    RingIcons.RotationRate,
    RingIcons.Clock,
    RingIcons.Wind,
    RingIcons.Flag,
    RingIcons.Moon,
    RingIcons.Calendar,
    RingIcons.Star,
    RingIcons.CloudSun,
    RingIcons.CloudSunSun,
    RingIcons.CloudSunCloud,
    RingIcons.RainCloud,
    RingIcons.RainDrops,
    RingIcons.StormCloud,
    RingIcons.StormBolt,
    RingIcons.Rain,
    RingIcons.Snow,
    RingIcons.Storm,
    RingIcons.Fog,
    RingIcons.Thermometer,
    RingIcons.ChevronLeft,
    RingIcons.Freefly,
    RingIcons.HeadDown,
    RingIcons.BellyArch,
    RingIcons.Pencil,
    RingIcons.Zigzag,
    RingIcons.Cross,
    RingIcons.ChevronRight,
    RingIcons.ChevronUp,
    RingIcons.ChevronDown,
    RingIcons.Home,
    RingIcons.Lock,
    RingIcons.Record,
    RingIcons.Stop,
    RingIcons.Grid,
    RingIcons.Watch,
    RingIcons.Play,
    RingIcons.Pause,
    RingIcons.Phone,
)

internal val PORTABLE_COMPOSITE_ICON_STYLES: Map<String, CircleIconStyle> by lazy { mapOf(
    "cloud-sun" to CircleIconStyle(listOf(CircleIconLayer(RingIcons.CloudSunSun, CircleAccent.SUN), CircleIconLayer(RingIcons.CloudSunCloud, CircleAccent.CLOUD)), primaryAccent = CircleAccent.SUN),
    "rain" to CircleIconStyle(listOf(CircleIconLayer(RingIcons.RainCloud, CircleAccent.CLOUD), CircleIconLayer(RingIcons.RainDrops, CircleAccent.RAIN)), primaryAccent = CircleAccent.RAIN),
    "storm" to CircleIconStyle(listOf(CircleIconLayer(RingIcons.StormCloud, CircleAccent.CLOUD), CircleIconLayer(RingIcons.StormBolt, CircleAccent.DANGER)), primaryAccent = CircleAccent.DANGER),
) }
