import type { ProductEmitterPlugin, ProductIr } from "@v1d/product-spec";
import type { CircleKitShowcaseProductIr } from "./product.js";

export function showcaseKotlinEmitter(path: string): ProductEmitterPlugin {
  return {
    id: "showcase-kotlin",
    emit(product) {
      const showcase = requireShowcaseProduct(product);
      return [{
        id: "showcase-kotlin",
        path,
        mediaType: "text/x-kotlin",
        content: emitKotlin(showcase),
      }];
    },
  };
}

function requireShowcaseProduct(product: ProductIr): CircleKitShowcaseProductIr {
  if (product.id !== "circlekit-showcase" || !("showcase" in product)) {
    throw new Error("Showcase Kotlin emitter received another product");
  }
  return product as CircleKitShowcaseProductIr;
}

function emitKotlin(product: CircleKitShowcaseProductIr): string {
  const profiles = product.artifacts.map((artifact) =>
    `    ${enumName(artifact.id)}(${kotlinString(artifact.id)}),`).join("\n");
  const families = product.showcase.sections.map((section) =>
    `    ${enumName(section.id)}(${kotlinString(section.id)}, ${kotlinString(section.title)}, ${kotlinString(section.menuLabel)}, ${kotlinString(section.iconId)}),`)
    .join("\n");
  const cases = product.showcase.cases.map((item) => {
    const scenarios = item.scenarios.map((scenario) =>
      `                ShowcaseScenario(ShowcaseScenarioId(${kotlinString(scenario.id)}), ${kotlinString(scenario.label)}),`)
      .join("\n");
    return `        ShowcaseCase(
            id = ShowcaseCaseId(${kotlinString(item.id)}),
            family = ShowcaseFamily.${enumName(item.section)},
            title = ${kotlinString(item.title)},
            iconId = ${kotlinString(item.iconId)},
            scenarios = listOf(
${scenarios}
            ),
        ),`;
  }).join("\n");
  const trees = product.componentFamilies.flatMap(({ screen, family }) =>
    family.trees.map((tree) => {
      const components = tree.mounts.map(({ component }) => kotlinString(component)).join(", ");
      return `        ShowcaseComponentTree(${kotlinString(screen)}, ${kotlinString(tree.surface)}, listOf(${components})),`;
    })).join("\n");

  return `// Generated by showcase-product/src/generate.ts. Do not edit.
package io.v1d.circlekit.showcase.catalog

enum class ShowcaseArtifactProfile(val id: String) {
${profiles}
}

enum class ShowcaseFamily(
    val id: String,
    val title: String,
    val menuLabel: String,
    val iconId: String,
) {
${families}
}

object ShowcaseManifest {
    const val PRODUCT_ID: String = ${kotlinString(product.id)}
    const val PRODUCT_SPEC_VERSION: String = ${kotlinString(product.productSpecVersion)}

    val profiles: Set<String> = ShowcaseArtifactProfile.entries.mapTo(linkedSetOf(), ShowcaseArtifactProfile::id)

    val cases: List<ShowcaseCase> = listOf(
${cases}
    )

    val componentTrees: List<ShowcaseComponentTree> = listOf(
${trees}
    )

    fun find(caseId: ShowcaseCaseId): ShowcaseCase? = cases.find { it.id == caseId }

    fun find(caseId: ShowcaseCaseId, scenarioId: ShowcaseScenarioId): Pair<ShowcaseCase, ShowcaseScenario>? {
        val case = find(caseId) ?: return null
        return case to (case.scenarios.find { it.id == scenarioId } ?: return null)
    }
}
`;
}

function enumName(id: string): string {
  return id.replaceAll(/[^A-Za-z0-9]+/gu, "_").toUpperCase();
}

function kotlinString(value: string): string {
  return `"${value
    .replaceAll("\\", "\\\\")
    .replaceAll("\"", "\\\"")
    .replaceAll("\n", "\\n")}"`;
}
