import type { ProductEmitterPlugin, ProductIr } from "@v1d/product-spec";
import type { CircleKitShowcaseProductIr } from "./product.js";

export function showcaseKotlinEmitter(path: string): ProductEmitterPlugin {
  return {
    id: "showcase-kotlin",
    emit(product) {
      const showcase = requireShowcaseProduct(product);
      return [{
        id: "showcase-kotlin",
        path,
        mediaType: "text/x-kotlin",
        content: emitKotlin(showcase),
      }];
    },
  };
}

function requireShowcaseProduct(product: ProductIr): CircleKitShowcaseProductIr {
  if (product.id !== "circlekit-showcase" || !("showcase" in product)) {
    throw new Error("Showcase Kotlin emitter received another product");
  }
  return product as CircleKitShowcaseProductIr;
}

function emitKotlin(product: CircleKitShowcaseProductIr): string {
  const profiles = product.artifacts.map((artifact) =>
    `    ${enumName(artifact.id)}(${kotlinString(artifact.id)}),`).join("\n");
  const families = product.showcase.sections.map((section) =>
    `    ${enumName(section.id)}(${kotlinString(section.id)}, ${kotlinString(section.title)}, ${kotlinString(section.menuLabel)}, ${kotlinString(section.iconId)}),`)
    .join("\n");
  const cases = product.showcase.cases.map((item) => {
    const scenarios = item.scenarios.map((scenario) =>
      `                ShowcaseScenario(ShowcaseScenarioId(${kotlinString(scenario.id)}), ${kotlinString(scenario.label)}),`)
      .join("\n");
    return `        ShowcaseCase(
            id = ShowcaseCaseId(${kotlinString(item.id)}),
            family = ShowcaseFamily.${enumName(item.section)},
            title = ${kotlinString(item.title)},
            iconId = ${kotlinString(item.iconId)},
            scenarios = listOf(
${scenarios}
            ),
        ),`;
  }).join("\n");
  const trees = product.artifactScopes.map((scope) => {
    const components = scope.includedMounts
      .map(({ componentInstanceRef }) => kotlinString(componentInstanceRef)).join(", ");
    return `        ShowcaseComponentTree(${kotlinString(scope.artifactRef)}, ${kotlinString(scope.screenRef)}, ${kotlinString(scope.surface)}, listOf(${components})),`;
  }).join("\n");
  const artifactScreens = product.artifacts.map((artifact) =>
    `        ${kotlinString(artifact.id)} to listOf(${artifact.screenRefs.map(kotlinString).join(", ")}),`).join("\n");
  const nodeTypes = new Map(product.nodeTypes.map((node) => [node.id, node]));
  const nodes = product.nodes.map((node) =>
    `        ShowcaseNodeDescriptor(${kotlinString(node.id)}, ${kotlinString(node.nodeTypeRef)}, ${kotlinString(nodeTypes.get(node.nodeTypeRef)!.kind)}),`).join("\n");
  const ports = [...product.portRegistry.nodePorts, ...product.portRegistry.componentPorts].map((item) =>
    `        ShowcaseProductPort(${[
      kotlinString(item.ref), kotlinString(item.ownerKind), kotlinString(item.ownerId), kotlinString(item.typeRef),
      kotlinString(item.portId), kotlinString(item.direction), kotlinString(item.contractRef),
      kotlinString(item.boundary), String(item.required), kotlinString(item.purpose),
    ].join(", ")}),`).join("\n");
  const bindings = product.portRegistry.bindings.map((item) =>
    `        ShowcasePortBinding(${kotlinString(item.kind)}, ${kotlinString(item.from)}, ${kotlinString(item.to)}, ${kotlinString(item.purpose)}),`).join("\n");
  const demandEdges = product.portRegistry.demandEdges.map((item) =>
    `        ShowcaseDemandEdge(${kotlinString(item.kind)}, ${nullableKotlinString("artifactRef" in item ? item.artifactRef : undefined)}, ${nullableKotlinString("screenRef" in item ? item.screenRef : undefined)}, ${nullableKotlinString("surface" in item ? item.surface : undefined)}, ${nullableKotlinString("componentInstanceRef" in item ? item.componentInstanceRef : undefined)}, ${kotlinString(item.nodeInstanceRef)}, ${kotlinString(item.targetPortRef)}),`).join("\n");
  const renderContracts = product.componentRenderContracts.map((contract) => `        ShowcaseGeneratedRenderContract(
            componentInstanceRef = ${kotlinString(contract.componentInstanceRef)},
            componentTypeRef = ${kotlinString(contract.componentTypeRef)},
            scopes = listOf(${contract.scopes.map((scope) => `ShowcaseGeneratedRenderScope(${kotlinString(scope.artifactRef)}, ${kotlinString(scope.screenRef)}, ${kotlinString(scope.surface)}, ${kotlinString(scope.mountRef)})`).join(", ")}),
            inputs = listOf(${contract.inputs.map((input) => `ShowcaseGeneratedInputSlot(${kotlinString(input.inputPortRef)}, ${kotlinString(input.producerPortRef)}, ${kotlinString(input.contractRef)}, ${input.required})`).join(", ")}),
            events = listOf(${contract.events.map((event) => `ShowcaseGeneratedEventSlot(${kotlinString(event.eventPortRef)}, ${kotlinString(event.targetPortRef)}, ${kotlinString(event.contractRef)})`).join(", ")}),
        ),`).join("\n");
  return `// Generated by showcase-product/src/generate.ts. Do not edit.
package io.v1d.circlekit.showcase.catalog

data class ShowcaseGeneratedRenderScope(
    val artifactRef: String,
    val screenRef: String,
    val surface: String,
    val mountRef: String,
)

data class ShowcaseGeneratedInputSlot(
    val consumerPortRef: String,
    val producerPortRef: String,
    val contractRef: String,
    val required: Boolean,
)

data class ShowcaseGeneratedEventSlot(
    val sourcePortRef: String,
    val targetPortRef: String,
    val contractRef: String,
)

data class ShowcaseGeneratedRenderContract(
    val componentInstanceRef: String,
    val componentTypeRef: String,
    val scopes: List<ShowcaseGeneratedRenderScope>,
    val inputs: List<ShowcaseGeneratedInputSlot>,
    val events: List<ShowcaseGeneratedEventSlot>,
)

class ShowcaseGeneratedImmutableInputBundle private constructor(
    val contract: ShowcaseGeneratedRenderContract,
    private val values: Map<String, Any>,
) {
    @Suppress("UNCHECKED_CAST")
    fun <T : Any> require(consumerPortRef: String): T =
        requireNotNull(values[consumerPortRef]) { "Missing immutable Showcase input '$consumerPortRef'" } as T

    companion object {
        fun exact(
            contract: ShowcaseGeneratedRenderContract,
            values: Map<String, Any>,
        ): ShowcaseGeneratedImmutableInputBundle {
            val expected = contract.inputs.mapTo(linkedSetOf(), ShowcaseGeneratedInputSlot::consumerPortRef)
            require(values.keys == expected) {
                "Renderer \${contract.componentInstanceRef} input keys \${values.keys} do not equal $expected"
            }
            return ShowcaseGeneratedImmutableInputBundle(contract, values.toMap())
        }
    }
}

enum class ShowcaseArtifactProfile(val id: String) {
${profiles}
}

enum class ShowcaseFamily(
    val id: String,
    val title: String,
    val menuLabel: String,
    val iconId: String,
) {
${families}
}

object ShowcaseManifest {
    const val PRODUCT_ID: String = ${kotlinString(product.id)}
    const val PRODUCT_SPEC_VERSION: String = ${kotlinString(product.productSpecVersion)}

    val profiles: Set<String> = ShowcaseArtifactProfile.entries.mapTo(linkedSetOf(), ShowcaseArtifactProfile::id)

    val artifactScreens: Map<String, List<String>> = linkedMapOf(
${artifactScreens}
    )

    val cases: List<ShowcaseCase> = listOf(
${cases}
    )

    val componentTrees: List<ShowcaseComponentTree> = listOf(
${trees}
    )

    val nodes: List<ShowcaseNodeDescriptor> = listOf(
${nodes}
    )

    val ports: List<ShowcaseProductPort> = listOf(
${ports}
    )

    val bindings: List<ShowcasePortBinding> = listOf(
${bindings}
    )

    val demandEdges: List<ShowcaseDemandEdge> = listOf(
${demandEdges}
    )

    val rendererContracts: List<ShowcaseGeneratedRenderContract> = listOf(
${renderContracts}
    )

    fun screensFor(profileId: String): List<String> = artifactScreens[profileId].orEmpty()

    fun componentIds(profileId: String, screenId: String): List<String> = componentTrees
        .filter { it.artifactProfileId == profileId && it.screenId == screenId }
        .flatMap(ShowcaseComponentTree::componentIds)
        .filter { id -> cases.any { it.id.value == id } }
        .distinct()

    fun find(caseId: ShowcaseCaseId): ShowcaseCase? = cases.find { it.id == caseId }

    fun find(caseId: ShowcaseCaseId, scenarioId: ShowcaseScenarioId): Pair<ShowcaseCase, ShowcaseScenario>? {
        val case = find(caseId) ?: return null
        return case to (case.scenarios.find { it.id == scenarioId } ?: return null)
    }
}
`;
}

function enumName(id: string): string {
  return id.replaceAll(/[^A-Za-z0-9]+/gu, "_").toUpperCase();
}

function kotlinString(value: string): string {
  return `"${value
    .replaceAll("\\", "\\\\")
    .replaceAll("\"", "\\\"")
    .replaceAll("\n", "\\n")}"`;
}

function nullableKotlinString(value: string | undefined): string {
  return value === undefined ? "null" : kotlinString(value);
}
