import type { ProductEmitterPlugin, ProductIr } from "@v1d/product-spec";
import type { CircleKitShowcaseProductIr } from "./product.js";

const GARMIN_LIMITED_UI = {
  screen: "section.controls",
  surface: "round",
  component: "control.progress",
  scenario: "half",
  palette: "sea-glass",
  componentRenderers: new Map([["control.progress", 1]]),
  iconRenderers: new Map([["download", 1]]),
  paletteRenderers: new Map([["sea-glass", 1]]),
} as const;

export function showcaseGarminEmitter(path: string): ProductEmitterPlugin {
  return {
    id: "showcase-garmin-limited-ui",
    emit(product) {
      const showcase = requireShowcaseProduct(product);
      const selection = selectLimitedUi(showcase);
      return [{
        id: "showcase-garmin-limited-ui",
        path,
        mediaType: "text/x-monkey-c",
        content: emitMonkeyC(showcase, selection),
      }];
    },
  };
}

interface GarminSelection {
  readonly componentId: string;
  readonly componentLabel: string;
  readonly componentOrder: number;
  readonly scenarioId: string;
  readonly scenarioLabel: string;
  readonly paletteRef: string;
  readonly iconRef: string;
  readonly componentRenderer: number;
  readonly paletteRenderer: number;
  readonly iconRenderer: number;
}

function requireShowcaseProduct(product: ProductIr): CircleKitShowcaseProductIr {
  if (product.id !== "circlekit-showcase" || !("showcase" in product)) {
    throw new Error("Showcase Garmin emitter received another product");
  }
  if (!product.ui.some((entry) =>
    entry.kind === "component-entry" && entry.requiredCapabilities.includes("ui.component-tree"))) {
    throw new Error("Showcase Garmin emitter requires ui.component-tree");
  }
  return product as CircleKitShowcaseProductIr;
}

function selectLimitedUi(product: CircleKitShowcaseProductIr): GarminSelection {
  const family = product.componentFamilies.find(({ screen }) => screen === GARMIN_LIMITED_UI.screen);
  const tree = family?.family.trees.find(({ surface }) => surface === GARMIN_LIMITED_UI.surface);
  if (tree === undefined) throw new Error("Garmin limited UI has no ROUND component tree");

  const mount = tree.mounts.find(({ component }) => component === GARMIN_LIMITED_UI.component);
  if (mount === undefined) throw new Error(`Garmin component '${GARMIN_LIMITED_UI.component}' is not mounted`);
  const componentRenderer = GARMIN_LIMITED_UI.componentRenderers.get(mount.component);
  if (componentRenderer === undefined) {
    throw new Error(`Garmin has no renderer for component '${mount.component}'`);
  }

  const component = product.showcase.cases.find(({ id }) => id === mount.component);
  const scenario = component?.scenarios.find(({ id }) => id === GARMIN_LIMITED_UI.scenario);
  if (component === undefined || scenario === undefined) {
    throw new Error(`Garmin component '${mount.component}' lacks scenario '${GARMIN_LIMITED_UI.scenario}'`);
  }
  const iconRenderer = GARMIN_LIMITED_UI.iconRenderers.get(component.iconId);
  if (iconRenderer === undefined) {
    throw new Error(`Garmin has no renderer for icon '${component.iconId}'`);
  }

  const palette = product.showcase.cases
    .find(({ id }) => id === "foundation.colors")
    ?.scenarios.find(({ id }) => id === GARMIN_LIMITED_UI.palette);
  const paletteRenderer = palette === undefined
    ? undefined
    : GARMIN_LIMITED_UI.paletteRenderers.get(palette.id);
  if (palette === undefined || paletteRenderer === undefined) {
    throw new Error(`Garmin has no renderer for palette '${GARMIN_LIMITED_UI.palette}'`);
  }

  return {
    componentId: mount.component,
    componentLabel: component.title,
    componentOrder: mount.order,
    scenarioId: scenario.id,
    scenarioLabel: scenario.label,
    paletteRef: palette.id,
    iconRef: component.iconId,
    componentRenderer,
    paletteRenderer,
    iconRenderer,
  };
}

function emitMonkeyC(product: CircleKitShowcaseProductIr, selection: GarminSelection): string {
  const productLabel = product.id.split("-")[0]?.toUpperCase() ?? product.id.toUpperCase();
  return `// Generated by showcase-product/src/generate.ts. Do not edit.
module GeneratedCircleKitShowcase {
    const PRODUCT_ID = ${monkeyString(product.id)};
    const PRODUCT_LABEL = ${monkeyString(productLabel)};
    const PRODUCT_SPEC_VERSION = ${monkeyString(product.productSpecVersion)};
    const SCREEN_ID = ${monkeyString(GARMIN_LIMITED_UI.screen)};
    const SURFACE_CLASS = ${monkeyString(GARMIN_LIMITED_UI.surface)};
    const SURFACE_LABEL = ${monkeyString(GARMIN_LIMITED_UI.surface.toUpperCase())};
    const COMPONENT_ID = ${monkeyString(selection.componentId)};
    const COMPONENT_ID_LABEL = ${monkeyString(selection.componentId.toUpperCase())};
    const COMPONENT_LABEL = ${monkeyString(selection.componentLabel)};
    const COMPONENT_ORDER = ${selection.componentOrder};
    const COMPONENT_ORDER_LABEL = ${monkeyString(`ORDER ${selection.componentOrder}`)};
    const COMPONENT_RENDERER = ${selection.componentRenderer};
    const SCENARIO_ID = ${monkeyString(selection.scenarioId)};
    const SCENARIO_LABEL = ${monkeyString(selection.scenarioLabel)};
    const PALETTE_REF = ${monkeyString(selection.paletteRef)};
    const FOOTER_LABEL = ${monkeyString(`${selection.paletteRef.toUpperCase()}  ORDER ${selection.componentOrder}`)};
    const ICON_REF = ${monkeyString(selection.iconRef)};
    const PALETTE_RENDERER = ${selection.paletteRenderer};
    const ICON_RENDERER = ${selection.iconRenderer};
}
`;
}

function monkeyString(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"").replaceAll("\n", "\\n")}"`;
}
